backend/apps/iamstudent/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('student_registration', views.get_student, name='student_registration'),
    path("thanks", views.thx, name="thanks"),
    # path('send_mail_student', views.send_mail_student, name='send_mail_student'),
    path("successful_mail", views.successful_mail, name="success"),
    # path('students_testing/<countrycode>/<plz>/<int:distance>', views.student_list_view, name='student_list_view'),
    path(
        "send_mail_student/<id_list>",
        views.send_mail_student_id_list,
        name="send_mail_student_id_list",
    ),
    path("view_student/<uuid>", views.view_student, name="view_student"),
]

backend/curaSWISS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from curaSWISS import views
from curaSWISS.settings import common as settings
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('mapview/', include('apps.mapview.urls')),
    path('iamstudent/', include('apps.iamstudent.urls')),
    path('ineedstudent/', include('apps.ineedstudent.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('impressum/', views.impressum),
    path('dataprotection/', views.dataprotection),
    path('legal-questions/', views.legal_questions),
    path('android-icon-144x144.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/android-icon-144x144.png'))),
    path('android-icon-192x192.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/android-icon-192x192.png'))),
    path('android-icon-36x36.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/android-icon-36x36.png'))),
    path('android-icon-48x48.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/android-icon-48x48.png'))),
    path('android-icon-72x72.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/android-icon-72x72.png'))),
    path('android-icon-96x96.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/android-icon-96x96.png'))),
    path('apple-icon-114x114.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-114x114.png'))),
    path('apple-icon-120x120.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-120x120.png'))),
    path('apple-icon-144x144.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-144x144.png'))),
    path('apple-icon-152x152.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-152x152.png'))),
    path('apple-icon-180x180.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-180x180.png'))),
    path('apple-icon-57x57.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-57x57.png'))),
    path('apple-icon-60x60.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-60x60.png'))),
    path('apple-icon-72x72.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-72x72.png'))),
    path('apple-icon-76x76.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-76x76.png'))),
    path('apple-icon-precomposed.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon-precomposed.png'))),
    path('apple-icon.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/apple-icon.png'))),
    path('favicon-16x16.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/favicon-16x16.png'))),
    path('favicon-32x32.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/favicon-32x32.png'))),
    path('favicon-96x96.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/favicon-96x96.png'))),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/favicon.ico'))),
    path('ms-icon-144x144.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/ms-icon-144x144.png'))),
    path('ms-icon-150x150.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/ms-icon-150x150.png'))),
    path('ms-icon-310x310.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/ms-icon-310x310.png'))),
    path('ms-icon-70x70.png', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/ms-icon-70x70.png')))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

backend/apps/iamstudent/models.py
from datetime import datetime
import uuid

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.accounts.models import User
from apps.ineedstudent.models import Hospital
from apps.mapview.utils import plzs


def validate_semester(value):
    if value < 0:
        raise ValidationError(_("Semester darf nicht negativ sein"))
    else:
        return value


def validate_checkbox(value):
    pass
    # TODO: Remove in a manner that does not brake migrations!!! # noqa: T003


# class Bezahlung(models.IntegerChoices):
EGAL = 0
# TODO: im form ändern zu radio # noqa: T003
BEZAHLUNG = 1
UNENTGELTLICH = 2
DARF_NICHT_BEZAHLT_WERDEN = 3
BEZAHLUNG_CHOICES = (
    (UNENTGELTLICH, _("Ich freue mich über eine Vergütung, helfe aber auch ohne")),
    (BEZAHLUNG, _("Ich benötige eine Vergütung")),
    (DARF_NICHT_BEZAHLT_WERDEN, _("Ich möchte ohne Bezahlung helfen")),
)

NUR_BEZAHLUNG = 1
NUR_UNENTGELTLICH = 2
BEZAHLUNG_CHOICES_Filter = (
    (NUR_BEZAHLUNG, _("Helfende müssen eine Vergütung annehmen.")),
    (NUR_UNENTGELTLICH, _("Wir können keine Vergütung anbieten.")),
)


CHECKBOX_CHOICES = [
    ("unknown", _("egal")),
    ("true", _("muss")),
    # ('false', _('darf nicht')),
]


# class Verfuegbarkeiten(models.IntegerChoices):
TEN = 1
TWENTY = 2
THIRTY = 3
FOURTY = 4
VERFUEGBARKEIT_CHOICES = (
    (TEN, _("10h pro Woche")),
    (TWENTY, _("20h pro Woche")),
    (THIRTY, _("30h pro Woche")),
    (FOURTY, _("40h pro Woche")),
)


class Ampel(models.IntegerChoices):
    ROT = 1
    GELB = 2
    GRUEN = 3


# class Umkreise(models.IntegerChoices):
LESSTEN = 1
LESSTWENTY = 2
LESSFOURTY = 3
MOREFOURTY = 4
UMKREIS_CHOICES = (
    (LESSTEN, _("<10 km")),
    (LESSTWENTY, _("<20 km")),
    (LESSFOURTY, _("<40 km")),
    (MOREFOURTY, _(">40 km")),
)
COUNTRY_CODE_CHOICES = [
    ("DE", _("Deutschland")),
    ("AT", _("Österreich")),
]


class Student(models.Model):

    # Database stuff
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    countrycode = models.CharField(max_length=2, choices=COUNTRY_CODE_CHOICES, default="DE",)
    # Allgemeines

    # vorerkrankungen
    # Berufserfahrung

    # TODO: add more validators! # noqa: T003

    # Bezahlung

    uuid = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    registration_date = models.DateTimeField(default=datetime.now, blank=True, null=True)

    name_first = models.CharField(max_length=50, default="")
    name_last = models.CharField(max_length=50, default="")
    phone_number = models.CharField(max_length=100, blank=True, default="")

    plz = models.CharField(max_length=5, null=True)
    umkreis = models.IntegerField(choices=UMKREIS_CHOICES, null=True, blank=False)
    availability_start = models.DateField(null=True, default=datetime.now)

    braucht_bezahlung = models.IntegerField(
        choices=BEZAHLUNG_CHOICES, default=UNENTGELTLICH
    )  # RADIO BUTTONS IM FORM!

    zeitliche_verfuegbarkeit = models.IntegerField(
        choices=VERFUEGBARKEIT_CHOICES, null=True, blank=False
    )

    datenschutz_zugestimmt = models.BooleanField(default=False)
    einwilligung_datenweitergabe = models.BooleanField(default=False)
    einwilligung_agb = models.BooleanField(default=False)

    sonstige_qualifikationen = models.CharField(max_length=200, blank=True, default="keine")
    unterkunft_gewuenscht = models.BooleanField(default=False)
    is_activated = models.BooleanField(default=True)

    # Metadata
    class Meta:
        ordering = ["plz"]

    # Methods
    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""  # noqa: D401
        return self.user.email

    def clean(self):
        if self.plz not in plzs[self.countrycode]:
            raise ValidationError(
                str(self.plz) + str(_(" ist keine Postleitzahl in ")) + self.countrycode
            )


"""Add stufff to model"""
wunschorte = [
    "arzt",
    "gesundheitsamt",
    "krankenhaus",
    "pflege",
    "rettungsdienst",
    "labor",
    "apotheke",
    "ueberall",
]
wunschorte_prefix = "wunsch_ort"
for w in wunschorte:
    Student.add_to_class(
        "%s_%s" % (wunschorte_prefix.lower(), w.lower()), models.BooleanField(default=False),
    )

# class MedstudAbschnitt(models.IntegerChoices):
KEINE_ANGABE = 0
VORKLINIK = 1
KLINIK = 2
PJ = 3
ASSIST = 4
FACH = 5
MEDSTUD_CHOICES = (
    (KEINE_ANGABE, _("Keine Angabe")),
    (VORKLINIK, _("Vorklinischer Teil")),
    (KLINIK, _("Klinischer Teil")),
    (PJ, _("Praktisches Jahr")),
    (ASSIST, _("Assistenzarzt")),
    (FACH, _("Facharzt")),
)


# class ZahnstudAbschnitt(models.IntegerChoices):
KEINE_ANGABE = 0
VORKLINIK = 1
KLINIK = 2
ABGESCHLOSSEN = 3
ZAHNSTUD_CHOICES = (
    (KEINE_ANGABE, _("Keine Angabe")),
    (VORKLINIK, _("Vorklinischer Teil")),
    (KLINIK, _("Klinischer Teil")),
    (ABGESCHLOSSEN, _("Abgeschlossen")),
)


# class MFAAbschnitt(models.IntegerChoices):
KEINE_ANGABE = 0
JAHR_1 = 1
JAHR_2 = 2
JAHR_3 = 3
BERUFSTAETIG = 4
MFA_CHOICES = (
    (KEINE_ANGABE, _("Keine Angabe")),
    (JAHR_1, _("1. Jahr")),
    (JAHR_2, _("2. Jahr")),
    (JAHR_3, _("3. Jahr")),
    (BERUFSTAETIG, _("Berufstätig")),
)

# class Ergotherapieauszubildende*r(models.IntegerChoices):
KEINE_ANGABE = 0
IN_AUSBILDUNG = 1
BERUFSTAETIG = 2
ERGOTHERAPIE_CHOICES = (
    (KEINE_ANGABE, _("Keine Angabe")),
    (IN_AUSBILDUNG, _("In Ausbildung")),
    (BERUFSTAETIG, _("Berufstätig")),
)


# class Psychologie/Psychotherapeut(models.IntegerChoices):
KEINE_ANGABE = 0
STUDIUM = 1
IN_AUSBILDUNG = 2
BERUFSTAETIG = 3
PSYCHO_CHOICES = (
    (KEINE_ANGABE, _("Keine Angabe")),
    (STUDIUM, _("Studium")),
    (IN_AUSBILDUNG, _("In Ausbildung")),
    (BERUFSTAETIG, _("Berufstätig")),
)


# class NOTFALLSANIAbschnitt(models.IntegerChoices):
KEINE_ANGABE = 0
JAHR_1 = 1
JAHR_2 = 2
BERUFSTAETIG = 4
NOTFALLSANI_CHOICES = (
    (KEINE_ANGABE, _("Keine Angabe")),
    (JAHR_1, _("1. Jahr")),
    (JAHR_2, _("2. Jahr")),
    (BERUFSTAETIG, _("Berufstätig")),
)
KEINE_ANGABE = 0
ERFAHR = 1
AUSBID_ABGESCHLOSSEN = 2
BETREU_CHOICES = (
    (KEINE_ANGABE, _("Keine Angabe")),
    (ERFAHR, _("Lediglich Erfahrungen")),
    (AUSBID_ABGESCHLOSSEN, _("Abgeschlossene Ausbildung")),
)


AUSBILDUNGS_TYPEN = {
    "MEDSTUD": {
        "abschnitt": (
            models.IntegerField,
            {"choices": MEDSTUD_CHOICES, "default": KEINE_ANGABE, "null": True},
        ),
        "famulaturen_anaesthesie": (models.BooleanField, {"default": False}),
        "famulaturen_chirurgie": (models.BooleanField, {"default": False}),
        "famulaturen_innere": (models.BooleanField, {"default": False}),
        "famulaturen_intensiv": (models.BooleanField, {"default": False}),
        "famulaturen_notaufnahme": (models.BooleanField, {"default": False}),
        "famulaturen_allgemeinmedizin": (models.BooleanField, {"default": False}),
        "empty_3": None,
        "anerkennung_noetig": (models.BooleanField, {"default": False}),
    },
    "MFA": {
        "abschnitt": (models.IntegerField, {"choices": MFA_CHOICES, "default": 0, "null": True},),
    },
    "MTLA": {
        "abschnitt": (models.IntegerField, {"choices": MFA_CHOICES, "default": 0, "null": True},),
    },
    "MTA": {
        "abschnitt": (models.IntegerField, {"choices": MFA_CHOICES, "default": 0, "null": True},),
    },
    "OTA": {
        "abschnitt": (models.IntegerField, {"choices": MFA_CHOICES, "default": 0, "null": True},),
    },
    "ATA": {
        "abschnitt": (models.IntegerField, {"choices": MFA_CHOICES, "default": 0, "null": True},),
    },
    "NOTFALLSANI": {
        "abschnitt": (
            models.IntegerField,
            {"choices": NOTFALLSANI_CHOICES, "default": 0, "null": True},
        ),
    },
    "PFLEGE": {
        "abschnitt": (models.IntegerField, {"choices": MFA_CHOICES, "default": 0, "null": True},),
    },
    "ERGOTHERAPIE": {
        "abschnitt": (
            models.IntegerField,
            {"choices": ERGOTHERAPIE_CHOICES, "default": 0, "null": True},
        ),
    },
    "PSYCHO": {
        "abschnitt": (
            models.IntegerField,
            {"choices": PSYCHO_CHOICES, "default": 0, "null": True},
        ),
    },
    "SANI": {},
    "HEBAMME": {},
    "FSJ": {},
    "ZAHNI": {
        "abschnitt": (
            models.IntegerField,
            {"choices": ZAHNSTUD_CHOICES, "default": 0, "null": True},
        ),
    },
    "PHYSIO": {
        "abschnitt": (models.IntegerField, {"choices": MFA_CHOICES, "default": 0, "null": True},),
    },
    "KINDERBETREUNG": {
        "ausgebildet_abschnitt": (
            models.IntegerField,
            {"choices": BETREU_CHOICES, "default": 0, "null": True},
        ),
    },
}

AUSBILDUNGS_IDS = dict(zip(AUSBILDUNGS_TYPEN.keys(), range(len(AUSBILDUNGS_TYPEN))))

AUSBILDUNGS_DETAIL_COLUMNS = []
for ausbildungs_typ, felder in AUSBILDUNGS_TYPEN.items():

    # types
    a_typ = "ausbildung_typ_%s" % ausbildungs_typ.lower()
    Student.add_to_class(a_typ, models.BooleanField(default=False))

    for key, field in felder.items():
        if "empty" in key:
            continue
        a_typ_kind = "ausbildung_typ_%s_%s" % (ausbildungs_typ.lower(), key.lower())
        AUSBILDUNGS_DETAIL_COLUMNS.append(a_typ_kind)
        Student.add_to_class(a_typ_kind, field[0](**field[1]))

# Generate Fields for translation
# print("{%s:_('')}"% ": _(''),".join(["'%s'" % c for c in columns]))

AUSBILDUNGS_TYPEN_COLUMNS = [
    "ausbildung_typ_%s" % ausbildungs_typ.lower() for ausbildungs_typ in AUSBILDUNGS_TYPEN
]


class EmailGroup(models.Model):
    subject = models.CharField(max_length=200, default="")
    message = models.TextField(default="", max_length=10000)
    uuid = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    registration_date = models.DateTimeField(default=datetime.now, blank=True, null=True)

backend/apps/iamstudent/models/email_group.py
from datetime import datetime
import uuid

from django.db import models

from apps.ineedstudent.models import Hospital


class EmailGroup(models.Model):
    subject = models.CharField(max_length=200, default="")
    message = models.TextField(default="", max_length=10000)
    uuid = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    registration_date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)

backend/apps/iamstudent/forms/emailtostudent.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from apps.iamstudent.models import EmailToSend


class EmailToSendForm(forms.ModelForm):
    class Meta:
        model = EmailToSend
        fields = ["subject", "message"]
        labels = {"subject": _("Betreff"), "message": _("Nachrichtentext")}
        help_texts = {}

    def clean_message(self):
        message = self.cleaned_data["message"]
        initial_message = self.initial["message"]
        if "".join(str(message).split()) == "".join(str(initial_message).split()):
            raise ValidationError(_("Bitte personalisiere diesen Text"), code="invalid")
        return message

backend/apps/iamstudent/views/emailtostudent_success.py
import logging

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView

from apps.accounts.admin import hospital_required

logger = logging.getLogger(__name__)


@method_decorator([login_required, hospital_required], name="dispatch")
class EmailToStudentSuccessView(TemplateView):

    template_name = "emails_sent.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["not_registered"] = not self.request.user.hospital.is_approved
        return context

backend/apps/iamstudent/views/student_detail.py
import logging

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic.base import View

from apps.accounts.admin import hospital_required
from apps.iamstudent.forms import StudentFormView
from apps.iamstudent.models import Student

logger = logging.getLogger(__name__)


@method_decorator([login_required, hospital_required], name="dispatch")
class StudentDetailView(View):
    def get(self, request):
        s = Student.objects.get(uuid=self.kwargs["uuid"])
        form = StudentFormView(instance=s, prefix="infos")
        context = {"form": form}
        return render(request, "view_student.html", context)

backend/apps/iamstudent/templates/ampel.html
<div class="btn-group">
    <button type="button" class="btn btn-sm bg-danger text-white" title="English">NIE</button>
    <button type="button" class="btn btn-sm bg-warning text-white" title="Deutsch">SELTEN</button>
    <button type="button" class="btn btn-sm bg-success text-white" title="idk">GUT</button>
</div>


{% if field.is_hidden %}
    {{ field }}
{% else %}
    <div id="div_{{ field.auto_id }}" class="form-group{% if 'form-horizontal' in form_class %} row{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors and field.errors %} has-danger{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">

        {% if field.label %}
            <label for="{{ field.id_for_label }}"  class="{{ label_class }}{% if not inline_class %} col-form-label{% endif %}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
    </div>
{% endif %}

backend/apps/iamstudent/templates/checkbox_studenttable.html
<input name="btSelectItem" type="checkbox">

backend/apps/iamstudent/templates/emails_sent.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
Helfende wurden Kontaktiert
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<hr>
<div class="container">
    <hr>
    <p>{% if not_registered %}
    {% blocktrans %} Wir speichern deine E-Mails und senden sie sobald wir dich als Krankenhaus validiert sind {%  endblocktrans %}
    {% else %}
    {% blocktrans %} Die Helfer*innen wurden kontaktiert. {% endblocktrans %}
    {% endif %}
<a href="/{{ LANGUAGE_CODE }}/mapview"> {% blocktrans %}Finde weitere Helfer*innen {% endblocktrans %}</a>
</p>
<hr>
</div>

{% endblock %}

backend/apps/iamstudent/templates/input_buttongroup-any_indicator.html
{% load crispy_forms_filters %}
{% load l10n %}
{% load i18n %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    <div id="div_{{ field.auto_id }}" class="form-group{% if using_grid_layout %} row{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors and field.errors %} has-danger{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        <div class="row">
        {% if field.label %}
        <div class="col">
            <label for="{{ field.auto_id }}"  class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label></div>
        {% endif %}
        <div class="col">
        <div class="btn-group" data-toggle="buttons" {% if flat_attrs %} {{ flat_attrs|safe }}{% endif %} >
            {% include 'bootstrap4/layout/field_errors_block.html' %}

             {% for choice in field.field.choices %}
                <button type="button" class="{% if choice.0|stringformat:"s" == field.value|stringformat:"s" %}active {% endif %}{{ option_label_class }}">
                    <input autocomplete="off" type="{{ input_type }}"{% if choice.0|stringformat:"s" == field.value|stringformat:"s" %} checked="checked"{% endif %} name="{{ field.html_name }}" id="id_{{ field.html_name }}_{{ forloop.counter }}" value="{{ choice.0|unlocalize }}" {{ field.field.widget.attrs|flatatt }} hidden >
                    {{choice.1}}
                </button>
            {% endfor %}

            {% include 'bootstrap4/layout/help_text.html' %}
        </div></div></div>

    </div>
{% endif %}

backend/apps/iamstudent/templates/input_buttongroup-egalmuss_indicator.html
{% load crispy_forms_filters %}
{% load l10n %}
{% load i18n %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    <div id="div_{{ field.auto_id }}" class="form-group{% if using_grid_layout %} row{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors and field.errors %} has-danger{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        <div class="row">
        {% if field.label %}
        <div class="col">
            <label for="{{ field.auto_id }}"  class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label></div>
        {% endif %}
        <div class="col">
        <div class="btn-group" data-toggle="buttons" {% if flat_attrs %} {{ flat_attrs|safe }}{% endif %} >
            {% include 'bootstrap4/layout/field_errors_block.html' %}
             {% for choice in field.field.choices %}
                {% if choice.0|stringformat:"s" ==  'false' %}
                    {# do not render the not wanted option autocomplete="off"#}
                {% else %}
                <label class="{% if choice.0|stringformat:"s" == field.value|stringformat:"s" %}active {% endif %}{% if field.value|stringformat:"s" == 'None'  %}{% if choice.0|stringformat:"s" == 'unknown' %}active {% endif %} {% endif %}{{ option_label_class }}">
                    <input autocomplete="off" type="{{ input_type }}"{% if choice.0|stringformat:"s" == field.value|stringformat:"s" %} checked="checked"{% endif %} name="{{ field.html_name }}" id="id_{{ field.html_name }}_{{ forloop.counter }}" value="{{ choice.0|unlocalize }}" {{ field.field.widget.attrs|flatatt }} hidden >
                    {{choice.1}}
                </label>
                {% endif %}
            {% endfor %}

            {% include 'bootstrap4/layout/help_text.html' %}
        </div></div></div>

    </div>
{% endif %}

backend/apps/iamstudent/templates/mail.html
{% load i18n %}

<h1>{% blocktrans %}Helfer*innen auswählen:{% endblocktrans %}</h1>
<form action="send_mail_student" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

backend/apps/iamstudent/templates/view_student.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">
<script type="text/javascript">

    var signUpHelper = {
        handleQualificationInput : function handleQualificationInput(event) {
            let sourceElement = event.srcElement;
            let qualificationSelected = event.srcElement.checked;

            // Extract qualification Id from parent div with suitable class, name ausbildung-checkbox-<id>
            let qualificationId = event.srcElement.closest("div.ausbildung-checkbox").id.split("-").slice(-1)
            this.setQualificationSectionVisibility(qualificationId, qualificationSelected)
        },
        setQualificationSectionVisibility : function setQualificationSectionVisibility(id, setVisibility) {
            let section = document.getElementById(`div-ausbildung-${id}`)
            if (!section) return;
            if (setVisibility) {
                section.classList.remove('hidden')
            } else {
                section.classList.add('hidden');
                section.querySelectorAll("input[type='checkbox']").forEach( (checkbox) => { checkbox.checked = false })
                section.querySelectorAll("input[type='text'], select").forEach( (textbox) => { textbox.value = '' })
            }

        },
    }

    document.addEventListener("DOMContentLoaded", function(event) {
        let qualifikationSelectors = document.querySelectorAll("div.ausbildung-checkbox input")
        qualifikationSelectors.forEach(element => {
            element.addEventListener("input", (event) => { signUpHelper.handleQualificationInput(event) })

            // To handle Mozillas brilliant idea to keep state of checkboxes on refresh, trigger dummy handler for every checkbox
            signUpHelper.handleQualificationInput({ srcElement: element });
        })

    });
</script>
{% endblock %}

{% block title %}
{% blocktrans %}Detailansicht Helfende*r {{ uuid }}{% endblocktrans %}
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<hr>
<div class="container">
    <div class="card border-primary">
        <div class="card-header">
            <h2>{% blocktrans %}Detailansicht Helfende*r{% endblocktrans %}</h2>
            <form action="view_student" method="post">
                {% csrf_token %}
                {% crispy form form.helper %}
            </form>
        </div>
        {{ student_form }}
    </div>
</div>
<hr>
<script type="text/javascript">
$( document ).ready(function() {
    $("#id_availability_start").attr("type", "date");
    $('.btn-group').attr('data-toggle','');
    //$('.btn-group input').attr('disabled','disabled');
    /*
    $(".btn-group").each(function(){
      console.log(jQuery._data( $(this), "events" ));
      console.log($(this))
      $(this).unbind();
    })*/
});

</script>
{% endblock %}